"""add skills

Revision ID: 0867c978de33
Revises: 9cabe49deed8
Create Date: 2026-09-18 18:12:39.922232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0867c978de33'
down_revision: Union[str, Sequence[str], None] = '9cabe49deed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_display_order'), 'skills', ['display_order'], unique=False)
    op.create_index(op.f('ix_skills_is_active'), 'skills', ['is_active'], unique=False)
    op.create_index(op.f('ix_skills_media_asset_id'), 'skills', ['media_asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_media_asset_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_is_active'), table_name='skills')
    op.drop_index(op.f('ix_skills_display_order'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
