"""create project tables

Revision ID: 194a41abfc33
Revises: 868da4dcedcf
Create Date: 2026-09-17 17:29:15.211077

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "194a41abfc33"
down_revision: str | Sequence[str] | None = "868da4dcedcf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("project_type", sa.String(length=120), nullable=False),
        sa.Column("short_description", sa.String(length=500), nullable=False),
        sa.Column("long_description", sa.Text(), nullable=False),
        sa.Column("project_date", sa.Date(), nullable=False),
        sa.Column("cover_media_asset_id", sa.Integer(), nullable=True),
        sa.Column("github_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "show_github_link", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column("demo_url", sa.String(length=2048), nullable=True),
        sa.Column("is_featured", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cover_media_asset_id"], ["media_assets.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_projects_cover_media_asset_id"),
        "projects",
        ["cover_media_asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_projects_display_order"), "projects", ["display_order"], unique=False
    )
    op.create_index(
        op.f("ix_projects_is_published"), "projects", ["is_published"], unique=False
    )
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=True)
    op.create_table(
        "project_features",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=500), nullable=False),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_features_project_id"),
        "project_features",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "project_images",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("media_asset_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["media_asset_id"], ["media_assets.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "media_asset_id", name="uq_project_images_project_asset"
        ),
    )
    op.create_index(
        op.f("ix_project_images_media_asset_id"),
        "project_images",
        ["media_asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_images_project_id"),
        "project_images",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "project_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "label", name="uq_project_tags_project_label"
        ),
    )
    op.create_index(
        op.f("ix_project_tags_project_id"), "project_tags", ["project_id"], unique=False
    )
    op.create_table(
        "project_tech_groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "label", name="uq_project_tech_groups_project_label"
        ),
    )
    op.create_index(
        op.f("ix_project_tech_groups_project_id"),
        "project_tech_groups",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "project_videos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("mux_upload_id", sa.String(length=255), nullable=True),
        sa.Column("mux_asset_id", sa.String(length=255), nullable=True),
        sa.Column("mux_playback_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status", sa.String(length=40), server_default="waiting", nullable=False
        ),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("aspect_ratio", sa.String(length=20), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mux_asset_id"),
        sa.UniqueConstraint("mux_playback_id"),
        sa.UniqueConstraint("mux_upload_id"),
    )
    op.create_index(
        op.f("ix_project_videos_project_id"),
        "project_videos",
        ["project_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_project_videos_status"), "project_videos", ["status"], unique=False
    )
    op.create_table(
        "project_tech_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tech_group_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["tech_group_id"], ["project_tech_groups.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tech_group_id", "name", name="uq_project_tech_items_group_name"
        ),
    )
    op.create_index(
        op.f("ix_project_tech_items_tech_group_id"),
        "project_tech_items",
        ["tech_group_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_tech_items_tech_group_id"), table_name="project_tech_items"
    )
    op.drop_table("project_tech_items")
    op.drop_index(op.f("ix_project_videos_status"), table_name="project_videos")
    op.drop_index(op.f("ix_project_videos_project_id"), table_name="project_videos")
    op.drop_table("project_videos")
    op.drop_index(
        op.f("ix_project_tech_groups_project_id"), table_name="project_tech_groups"
    )
    op.drop_table("project_tech_groups")
    op.drop_index(op.f("ix_project_tags_project_id"), table_name="project_tags")
    op.drop_table("project_tags")
    op.drop_index(op.f("ix_project_images_project_id"), table_name="project_images")
    op.drop_index(op.f("ix_project_images_media_asset_id"), table_name="project_images")
    op.drop_table("project_images")
    op.drop_index(op.f("ix_project_features_project_id"), table_name="project_features")
    op.drop_table("project_features")
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_index(op.f("ix_projects_is_published"), table_name="projects")
    op.drop_index(op.f("ix_projects_display_order"), table_name="projects")
    op.drop_index(op.f("ix_projects_cover_media_asset_id"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
