"""add experiences

Revision ID: 606dbb58425d
Revises: 8fd86a86e7ef
Create Date: 2026-09-18 20:19:33.502502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '606dbb58425d'
down_revision: Union[str, Sequence[str], None] = '8fd86a86e7ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiences_display_order'), 'experiences', ['display_order'], unique=False)
    op.create_index(op.f('ix_experiences_is_active'), 'experiences', ['is_active'], unique=False)
    op.create_table('experience_highlights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_highlights_experience_id'), 'experience_highlights', ['experience_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_experience_highlights_experience_id'), table_name='experience_highlights')
    op.drop_table('experience_highlights')
    op.drop_index(op.f('ix_experiences_is_active'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_display_order'), table_name='experiences')
    op.drop_table('experiences')
    # ### end Alembic commands ###
