"""create media library tables

Revision ID: 868da4dcedcf
Revises: 8b2b88f7b7d0
Create Date: 2026-09-17 14:45:00.071632

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "868da4dcedcf"
down_revision: str | Sequence[str] | None = "8b2b88f7b7d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_assets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_type", sa.String(length=20), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("alt_text", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_media_assets_file_type"), "media_assets", ["file_type"], unique=False
    )
    op.create_index(
        op.f("ix_media_assets_storage_key"),
        "media_assets",
        ["storage_key"],
        unique=True,
    )
    op.create_table(
        "media_variants",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("media_asset_id", sa.Integer(), nullable=False),
        sa.Column("variant_name", sa.String(length=50), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["media_asset_id"], ["media_assets.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "media_asset_id", "variant_name", name="uq_media_variants_asset_name"
        ),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        op.f("ix_media_variants_media_asset_id"),
        "media_variants",
        ["media_asset_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_variants_media_asset_id"), table_name="media_variants")
    op.drop_table("media_variants")
    op.drop_index(op.f("ix_media_assets_storage_key"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_file_type"), table_name="media_assets")
    op.drop_table("media_assets")
    # ### end Alembic commands ###
