"""add contact content

Revision ID: 8fd86a86e7ef
Revises: 0867c978de33
Create Date: 2026-09-18 19:55:57.089656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd86a86e7ef'
down_revision: Union[str, Sequence[str], None] = '0867c978de33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('projects_built', sa.Integer(), server_default='0', nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone_number', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_contact_content_singleton_id'),
    sa.CheckConstraint('projects_built >= 0', name='ck_contact_content_projects_built_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_content')
    # ### end Alembic commands ###
