"""add about content

Revision ID: bc595f19f066
Revises: ede5f985e1c5
Create Date: 2026-09-18 16:47:16.456248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc595f19f066'
down_revision: Union[str, Sequence[str], None] = 'ede5f985e1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('profile_media_asset_id', sa.Integer(), nullable=True),
    sa.Column('resume_media_asset_id', sa.Integer(), nullable=True),
    sa.Column('about_html', sa.Text(), server_default='', nullable=False),
    sa.Column('experience_years', sa.Integer(), server_default='0', nullable=False),
    sa.Column('location', sa.String(length=255), server_default='', nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('availability_modes', postgresql.ARRAY(sa.String(length=20)), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('experience_years >= 0', name='ck_about_content_experience_years_nonnegative'),
    sa.ForeignKeyConstraint(['profile_media_asset_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_media_asset_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_about_content_profile_media_asset_id'), 'about_content', ['profile_media_asset_id'], unique=False)
    op.create_index(op.f('ix_about_content_resume_media_asset_id'), 'about_content', ['resume_media_asset_id'], unique=False)
    op.create_table('about_social_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('about_content_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['about_content_id'], ['about_content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('about_content_id', 'display_order', name='uq_about_social_links_content_order')
    )
    op.create_index(op.f('ix_about_social_links_about_content_id'), 'about_social_links', ['about_content_id'], unique=False)
    op.create_table('about_software_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('about_content_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['about_content_id'], ['about_content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('about_content_id', 'display_order', name='uq_about_software_fields_content_order')
    )
    op.create_index(op.f('ix_about_software_fields_about_content_id'), 'about_software_fields', ['about_content_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_about_software_fields_about_content_id'), table_name='about_software_fields')
    op.drop_table('about_software_fields')
    op.drop_index(op.f('ix_about_social_links_about_content_id'), table_name='about_social_links')
    op.drop_table('about_social_links')
    op.drop_index(op.f('ix_about_content_resume_media_asset_id'), table_name='about_content')
    op.drop_index(op.f('ix_about_content_profile_media_asset_id'), table_name='about_content')
    op.drop_table('about_content')
    # ### end Alembic commands ###
