"""add educations

Revision ID: c1f7f01af8e5
Revises: 606dbb58425d
Create Date: 2026-09-18 20:59:01.282870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1f7f01af8e5'
down_revision: Union[str, Sequence[str], None] = '606dbb58425d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('certification_media_asset_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['certification_media_asset_id'], ['media_assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_educations_certification_media_asset_id'), 'educations', ['certification_media_asset_id'], unique=False)
    op.create_index(op.f('ix_educations_display_order'), 'educations', ['display_order'], unique=False)
    op.create_index(op.f('ix_educations_is_active'), 'educations', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_educations_is_active'), table_name='educations')
    op.drop_index(op.f('ix_educations_display_order'), table_name='educations')
    op.drop_index(op.f('ix_educations_certification_media_asset_id'), table_name='educations')
    op.drop_table('educations')
    # ### end Alembic commands ###
