"""add testimonials

Revision ID: ede5f985e1c5
Revises: 9f4c2d7a1e63
Create Date: 2026-09-18 16:11:11.649384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede5f985e1c5'
down_revision: Union[str, Sequence[str], None] = '9f4c2d7a1e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_name', sa.String(length=200), nullable=False),
    sa.Column('testimonial_text', sa.Text(), nullable=False),
    sa.Column('profile_media_asset_id', sa.Integer(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=2048), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_media_asset_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testimonials_display_order'), 'testimonials', ['display_order'], unique=False)
    op.create_index(op.f('ix_testimonials_is_active'), 'testimonials', ['is_active'], unique=False)
    op.create_index(op.f('ix_testimonials_profile_media_asset_id'), 'testimonials', ['profile_media_asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_testimonials_profile_media_asset_id'), table_name='testimonials')
    op.drop_index(op.f('ix_testimonials_is_active'), table_name='testimonials')
    op.drop_index(op.f('ix_testimonials_display_order'), table_name='testimonials')
    op.drop_table('testimonials')
    # ### end Alembic commands ###
